# Generated by Django 5.1.2 on 2025-02-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('E_credits', models.IntegerField()),
                ('Uploaded_Documents', models.IntegerField()),
            ],
        ),
    ]
