# Generated by Django 5.1.2 on 2025-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
